eclipse-basyx/basyx-java-sdk

src/main/java/org/eclipse/basyx/submodel/metamodel/map/reference/Reference.java
src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/map/reference/TestReference.java

Dear Mr. Frank,
I have fixed the bug "Fixed bug of Reference.isReference throws Exception when working with raw maps." and added corresponding test case for replicating this issue.
Thanks and Regards
Mohammad

Fixed Reference.isReference throws Exception with raw maps

---

src/main/java/org/eclipse/basyx/submodel/metamodel/connected/submodelelement/ConnectedSubmodelElement.java
src/main/java/org/eclipse/basyx/submodel/metamodel/connected/submodelelement/dataelement/ConnectedBlob.java
src/main/java/org/eclipse/basyx/submodel/metamodel/connected/submodelelement/dataelement/ConnectedDataElement.java
src/main/java/org/eclipse/basyx/submodel/metamodel/connected/submodelelement/dataelement/ConnectedFile.java
src/main/java/org/eclipse/basyx/submodel/metamodel/connected/submodelelement/dataelement/ConnectedMultiLanguageProperty.java
src/main/java/org/eclipse/basyx/submodel/metamodel/connected/submodelelement/dataelement/ConnectedProperty.java
src/main/java/org/eclipse/basyx/submodel/metamodel/connected/submodelelement/dataelement/ConnectedRange.java
src/main/java/org/eclipse/basyx/submodel/metamodel/connected/submodelelement/dataelement/ConnectedReferenceElement.java
src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/connected/submodelelement/SubmodelElementTestHelper.java
src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/connected/submodelelement/dataelement/TestConnectedBlob.java
src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/connected/submodelelement/dataelement/TestConnectedFile.java
src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/connected/submodelelement/dataelement/TestConnectedMultiLanguageProperty.java
src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/connected/submodelelement/dataelement/TestConnectedRange.java
src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/connected/submodelelement/dataelement/TestConnectedReferenceElement.java

Dear Mr. Frank
I have fixed the bug for "getValue caching from org.eclipse.basyx.submodel.metamodel.connected.submodelelement.dataelement" and added corresponding test cases for replicating this issue.
Thanks and Regards
Mohammad

Fixed getValue caching from org.eclipse.basyx.submodel.metamodel.connected.submodelelement.dataelement

---

src/main/java/org/eclipse/basyx/registry/descriptor/AASDescriptor.java
src/main/java/org/eclipse/basyx/registry/memory/MapRegistryHandler.java
src/main/java/org/eclipse/basyx/registry/memory/Registry.java
src/main/java/org/eclipse/basyx/registry/restapi/RegistryServerAPIHelper.java
src/test/java/org/eclipse/basyx/testsuite/regression/registry/TestRegistryProviderSuite.java

* Adds check for existing idShort in AASDescriptor
* Adds submodelDescriptors for shells as global
* Updates checks for identifiers
* Adds tests for these cases
* Adds test for idShort of submodel in shell
* Adds missing checks to avoid NullPointerExceptions to ServerAPIHelper
* Adds toString for better debugging to ServerAPIHelper

Adds missing features of registry v2

---

src/main/java/org/eclipse/basyx/submodel/restapi/OperationProvider.java
src/main/java/org/eclipse/basyx/submodel/restapi/operation/DelegatedInvocationManager.java
src/test/java/org/eclipse/basyx/testsuite/regression/submodel/restapi/OperationProviderTest.java

Refactors DelegatedInvocationHelper to be able to use custom IConnectorFactory for delegated invokations
Renames DelegatedInvocationHelper to DelegatedInvocationManager
Signed-off-by: Maximilian Conradi <maximilian.conradi@iese.fraunhofer.de>

Refactors DelegatedInvocationHelper to accept IConnectorFactory

---

src/main/java/org/eclipse/basyx/extensions/aas/aggregator/authorization/AuthorizedAASAggregatorProxy.java
src/main/java/org/eclipse/basyx/extensions/aas/manager/authorized/AuthorizedConnectedAASManager.java
src/main/java/org/eclipse/basyx/extensions/aas/registration/authorization/AuthorizedAASRegistryProxy.java
src/main/java/org/eclipse/basyx/vab/protocol/https/HTTPSConnector.java
src/main/java/org/eclipse/basyx/vab/protocol/https/HTTPSConnectorProvider.java

It uses HTTPSConnector and IAuthorizationSupplier per default
Co-authored-by: Daniel Espen <Daniel.Espen@iese.fraunhofer.de>
Signed-off-by: Zai Müller-Zhang <zai.mueller-zhang@iese.fraunhofer.de>

Add authorized variant of ConnectedAssetAdministrationShellManager

---

src/main/java/org/eclipse/basyx/submodel/metamodel/api/qualifier/haskind/IHasKind.java
src/main/java/org/eclipse/basyx/submodel/metamodel/connected/ConnectedSubmodel.java
src/main/java/org/eclipse/basyx/submodel/metamodel/connected/submodelelement/ConnectedSubmodelElement.java
src/main/java/org/eclipse/basyx/submodel/metamodel/map/Submodel.java
src/main/java/org/eclipse/basyx/submodel/metamodel/map/qualifier/haskind/HasKind.java
src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/SubmodelElement.java
src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/map/qualifier/haskind/TestHasKind.java

Refactored HasKind to be aligned with AAS Spec, where ModelingKind is held by attribute "kind" - not "modelingKind".
Additionally a NullPointerException is fixed, which occurs when kind is set to null

Refactored HasKind and fixing NullPointerException

---

src/main/java/org/eclipse/basyx/vab/exception/provider/ProviderException.java

- Messages of ProviderException are also passed as message for RuntimeException

Adds better handling of Exception messages

---

src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/dataelement/property/Property.java
src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/map/submodelelement/dataelement/property/TestProperty.java

Property.valueId is optional - so setting it to null shouldn't result in a NullPointerException.

Fixing NullPointerException on Property.setValueId(null)

---

src/main/java/org/eclipse/basyx/aas/factory/aasx/AASXToMetamodelConverter.java
src/main/java/org/eclipse/basyx/aas/factory/aasx/FileLoaderHelper.java

Dear Frank,
This PR adds helper class FileLoaderHelper
Description:
- Removes getInputStream method from AASXToMetamodelConverter
- Adds helper class FileLoaderHelper to facilitate loading of files

Adds helper class FileLoaderHelper

---

src/main/java/org/eclipse/basyx/aas/aggregator/AASAggregator.java
src/main/java/org/eclipse/basyx/aas/manager/ConnectedAssetAdministrationShellManager.java
src/main/java/org/eclipse/basyx/aas/restapi/AASAPIFactory.java
src/main/java/org/eclipse/basyx/aas/restapi/MultiSubmodelProvider.java
src/main/java/org/eclipse/basyx/aas/restapi/api/IAASAPIFactory.java
src/main/java/org/eclipse/basyx/extensions/aas/api/authorization/AuthorizedDecoratingAASAPIFactory.java
src/main/java/org/eclipse/basyx/extensions/aas/api/mqtt/MqttDecoratingAASAPIFactory.java
src/main/java/org/eclipse/basyx/extensions/submodel/authorization/AuthorizedDecoratingSubmodelAPIFactory.java
src/main/java/org/eclipse/basyx/extensions/submodel/mqtt/MqttDecoratingSubmodelAPIFactory.java
src/main/java/org/eclipse/basyx/submodel/aggregator/SubmodelAggregator.java
src/main/java/org/eclipse/basyx/submodel/aggregator/api/ISubmodelAggregatorFactory.java
src/main/java/org/eclipse/basyx/submodel/restapi/api/ISubmodelAPIFactory.java
src/main/java/org/eclipse/basyx/submodel/restapi/operation/DelegatedInvocationManager.java
src/main/java/org/eclipse/basyx/vab/factory/java/ModelProxyFactory.java
src/main/java/org/eclipse/basyx/vab/gateway/ConnectorProviderMapper.java
src/main/java/org/eclipse/basyx/vab/protocol/api/IConnectorFactory.java

Dear Frank,
This PR adds create method in interfaces.
Description:
- Adds create method in IAASAPIFactory and marks getAASApi as deprecated
- Adds create method in IConnectorFactory and marks getConnector as deprecated
- Adds create method in ISubmodelAPIFactory and marks getSubmodelAPI as deprecated

Adds create method in interfaces

---

.github/workflows/maven-publish-snapshot.yml

Dear Frank,
Following was the issue with earlier version of delete-package-versions@v1 :
```
Run actions/delete-package-versions@v1
with:
package-name: org.eclipse.basyx.basyx.sdk
num-old-versions-to-delete: 1
token: ***
env:
JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64
Error: delete version mutation failed. Type mismatch on variable $packageVersionId and argument packageVersionId (String! / ID!)
```
This issue was found and fixed in v2. Issue link : #https://github.com/actions/delete-package-versions/issues/66#issuecomment-1055207022
Fixed by : #https://github.com/actions/delete-package-versions/pull/67
I have updated delete package version from v1 to v3 and this issue is not reproducible and old package is getting deleted.
Following is the log of successful deletion in …

Fixes GitHub Action does not delete old packages

---

src/main/java/org/eclipse/basyx/extensions/aas/api/mqtt/MqttAASAPIHelper.java
src/main/java/org/eclipse/basyx/extensions/aas/api/mqtt/MqttAASAPIObserver.java
src/main/java/org/eclipse/basyx/extensions/aas/api/mqtt/MqttDecoratingAASAPIFactory.java
src/main/java/org/eclipse/basyx/extensions/submodel/mqtt/MqttDecoratingSubmodelAPIFactory.java
src/main/java/org/eclipse/basyx/extensions/submodel/mqtt/MqttSubmodelAPI.java
src/main/java/org/eclipse/basyx/extensions/submodel/mqtt/MqttSubmodelAPIHelper.java
src/main/java/org/eclipse/basyx/extensions/submodel/mqtt/MqttSubmodelAPIObserver.java
src/test/java/org/eclipse/basyx/testsuite/regression/extensions/submodel/mqtt/MqttSubmodelAPIObserverTest.java

Description:
- Refactors MqttAASAPIObserver by adding two new constructors (1 additional due to credentials)
- Refactors MqttSubmodelAPIObserver by adding two new constructors (1 additional due to credentials)
Signed-off-by: Mohammad Ghazanfar Ali Danish ghazanfar.danish@iese.fraunhofer.de

Refactor MqttObservers to not add themselves

---

src/main/java/org/eclipse/basyx/submodel/restapi/SubmodelProvider.java
src/test/java/org/eclipse/basyx/testsuite/regression/submodel/restapi/SubmodelProviderTest.java

Operation invocations used to fail with a `ResourceNotFound` exception when the query parameter `async` is explicitly set to `false`.
For example: `POST http://host/submodels/mySubmodel/submodel/submodelElements/myOperation/invoke?async=false`.
That's because `SubmodelProvider` deleted the first mention of `invoke` from the URL, leaving the `?async=false` behind.
This should work as expected now, making a synchronous request.

Fix synchronous operation invocation

---

src/main/java/org/eclipse/basyx/extensions/aas/directory/tagged/map/MapTaggedDirectory.java
src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/directory/tagged/TestTaggedDirectorySuite.java

Since polymorph model extensions are not detected, we should test if there are submitted values.

Instead of applying instanceof filter, check for submitted values

---

src/main/java/org/eclipse/basyx/submodel/metamodel/connected/submodelelement/operation/ConnectedAsyncInvocation.java

Fix  response object map to be used as invocation response in async operation
* It seems that "result" was used instead of "responseObj", but makes no sense here in my opinion.
* "result" map cannot be converted to invocation response.
* Instead changed to "responseObj" which can be a map if requested via rest call from remote submodel api.
Signed-off-by: Matthias Stöhr <matthias.stoehr@ipa.fraunhofer.de>

Fix  response object map to be used as invocation response in async operation

---

src/main/java/org/eclipse/basyx/vab/protocol/http/server/BaSyxHTTPServer.java

[Feature Request]
https://github.com/eclipse-basyx/basyx-java-components/issues/124 
The health endpoint can be directly accessed by host/health.
For e.g if the AAS registry is hosted at http://localhost:4000 then the health endpoint would be http://localhost:4000/health
This endpoint will return 200 OK if everything is up and running.

Configure health endpoint for AAS Registry and AAS Server

---

src/main/java/org/eclipse/basyx/aas/factory/xml/AASXPackageExplorerCompatibilityHandler.java
src/test/java/org/eclipse/basyx/testsuite/regression/aas/factory/aasx/TestMetamodelToAASXConverter.java

When an OpertionVariable in AASX is empty the converter throws an Exception. The generated aasx (using BaSyx Converter) looks OK.
```
<aas:operation>
...
<aas:inoutputVariable/>
...
</aas:operation>
```

Fixes empty operation variables

---

src/main/java/org/eclipse/basyx/extensions/aas/aggregator/mqtt/MqttAASAggregatorHelper.java
src/main/java/org/eclipse/basyx/extensions/aas/registration/mqtt/MqttAASRegistryHelper.java
src/main/java/org/eclipse/basyx/extensions/aas/registration/mqtt/MqttAASRegistryService.java
src/main/java/org/eclipse/basyx/extensions/aas/registration/mqtt/MqttAASRegistryServiceObserver.java
src/main/java/org/eclipse/basyx/extensions/submodel/mqtt/MqttSubmodelAPIObserver.java
src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/registration/mqtt/TestMqttAASRegistryService.java
src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/registration/mqtt/TestMqttAASRegistryServiceObserver.java
src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/registration/mqtt/TestMqttAASRegistryServicePayloadParser.java

Add java doc to method in Mqtt*Helper.
Revert breaking change in createSubmodelDescriptorOfAASChangedPayload() in MqttAASRegistryHelper class. Mark getCombinedMessage() as deprecated.
Signed-off-by: Zai Zhang <zai.mueller-zhang@iese.fraunhofer.de>

Refactor Commit "Externalize Mqtt payload to Helper classes"

---

pom.xml
src/main/java/org/eclipse/basyx/aas/factory/aasx/AASXToMetamodelConverter.java
src/main/java/org/eclipse/basyx/extensions/aas/aggregator/aasxupload/AASAggregatorAASXUpload.java
src/test/java/org/eclipse/basyx/testsuite/regression/aas/factory/aasx/TestAASXToMetamodelConverterFromBaSyx.java
src/test/java/org/eclipse/basyx/testsuite/regression/aas/factory/aasx/TestAASXToMetamodelConverterFromFile.java
src/test/java/org/eclipse/basyx/testsuite/regression/aas/factory/aasx/TestMetamodelToAASXConverter.java

- There have been many changes in poi-ooxml 5.x (https://poi.apache.org/changes.html)
- Some changes done related to closing of OPCPackage in poi-ooxml 5.x affecting basyx-java-sdk
- Adapts AASXToMetamodelConverter as per the changes in poi-ooxml 5.x
- Refactors test cases associated with the latest changes in AASXToMetamodelConverter i.e., releasing of resources.
- The changes in this PR is not a breaking change

Updates poi-ooxml to latest version (v5.2.3)

---

src/main/java/org/eclipse/basyx/extensions/aas/aggregator/aasxupload/AASAggregatorAASXUpload.java
src/main/java/org/eclipse/basyx/submodel/restapi/SubmodelProvider.java
src/test/java/org/eclipse/basyx/testsuite/regression/submodel/restapi/TestHttpFileUpload.java

The error was due to using the endpoint http://<server>:<port>/<contextPath>/shells/<aas-id>/.../<file-idShort>/upload now instead of http://<server>:<port>/<contextPath>/shells/<aas-id>/.../<file-idShort>/File/upload

fixed file upload bug and corresponding test
