eclipse-basyx/basyx-java-sdk

src/main/java/org/eclipse/basyx/aas/aggregator/AASAggregator.java, src/main/java/org/eclipse/basyx/aas/aggregator/api/IAASAggregator.java, src/main/java/org/eclipse/basyx/aas/aggregator/observing/ObservableAASAggregator.java, src/main/java/org/eclipse/basyx/aas/aggregator/proxy/AASAggregatorProxy.java, src/main/java/org/eclipse/basyx/aas/aggregator/restapi/AASAggregatorProvider.java, src/main/java/org/eclipse/basyx/aas/bundle/AASBundleHelper.java, src/main/java/org/eclipse/basyx/aas/manager/ConnectedAssetAdministrationShellManager.java, src/main/java/org/eclipse/basyx/extensions/aas/aggregator/aasxupload/AASAggregatorAASXUpload.java, src/main/java/org/eclipse/basyx/extensions/aas/aggregator/mqtt/MqttAASAggregator.java, src/test/java/org/eclipse/basyx/testsuite/regression/aas/aggregator/AASAggregatorSuite.java, src/test/java/org/eclipse/basyx/testsuite/regression/aas/aggregator/TestAASAggregatorProxy.java, src/test/java/org/eclipse/basyx/testsuite/regression/aas/aggregator/observing/ObservableAASAggregatorTest.java, src/test/java/org/eclipse/basyx/testsuite/regression/aas/bundle/TestAASBundleHelper.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/aggregator/mqtt/TestMqttAASAggregator.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/aggregator/mqtt/TestMqttAASAggregatorObserver.java
to achieve consistency with other methods in IAASAggregator
Signed-off-by: Rene-Pascal Fischer <rene-pascal.fischer@iese.fraunhofer.de>
=> Reverts renaming of wrong method

src/main/java/org/eclipse/basyx/extensions/aas/aggregator/mqtt/MqttAASAggregator.java, src/main/java/org/eclipse/basyx/extensions/aas/aggregator/mqtt/MqttAASAggregatorHelper.java, src/main/java/org/eclipse/basyx/extensions/aas/aggregator/mqtt/MqttAASAggregatorObserver.java, src/main/java/org/eclipse/basyx/extensions/aas/registration/mqtt/MqttAASRegistryHelper.java, src/main/java/org/eclipse/basyx/extensions/aas/registration/mqtt/MqttAASRegistryService.java, src/main/java/org/eclipse/basyx/extensions/aas/registration/mqtt/MqttAASRegistryServiceObserver.java, src/main/java/org/eclipse/basyx/extensions/submodel/mqtt/MqttSubmodelAPI.java, src/main/java/org/eclipse/basyx/extensions/submodel/mqtt/MqttSubmodelAPIHelper.java, src/main/java/org/eclipse/basyx/extensions/submodel/mqtt/MqttSubmodelAPIObserver.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/aggregator/mqtt/TestMqttAASAggregator.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/aggregator/mqtt/TestMqttAASAggregatorObserver.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/registration/mqtt/TestMqttAASRegistryService.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/registration/mqtt/TestMqttAASRegistryServiceObserver.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/submodel/mqtt/MqttSubmodelAPIObserverTest.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/submodel/mqtt/TestMqttSubmodelAPIEvents.java
Dear Frank,
Added helper classes for MqttAASRegistry, MqttAASAggregator, MqttSubmodelAPI and moved redundant codes in these classes.
Thanks and Regards
Mohammad Ghazanfar Ali Danish
=> Moved redundant codes in helper class.

src/test/java/org/eclipse/basyx/testsuite/regression/registry/TestRegistryProviderSuite.java
Removes unnecessary enumeration.
=> Removes system.out.print.line

src/main/java/org/eclipse/basyx/registry/memory/Registry.java
Signed-off-by: Rene-Pascal Fischer <rene-pascal.fischer@iese.fraunhofer.de>
=> Fixes bug where submodel was not deleted in shell

src/main/java/org/eclipse/basyx/aas/aggregator/AASAggregator.java, src/main/java/org/eclipse/basyx/aas/aggregator/observing/IAASAggregatorObserver.java, src/main/java/org/eclipse/basyx/aas/aggregator/observing/ObservableAASAggregator.java, src/main/java/org/eclipse/basyx/aas/registration/observing/IAASRegistryServiceObserver.java, src/main/java/org/eclipse/basyx/aas/registration/observing/ObservableAASRegistryService.java, src/main/java/org/eclipse/basyx/aas/restapi/MultiSubmodelProvider.java, src/main/java/org/eclipse/basyx/extensions/aas/aggregator/mqtt/MqttAASAggregator.java, src/main/java/org/eclipse/basyx/extensions/aas/aggregator/mqtt/MqttAASAggregatorObserver.java, src/main/java/org/eclipse/basyx/extensions/submodel/aggregator/mqtt/MqttSubmodelAggregator.java, src/main/java/org/eclipse/basyx/extensions/submodel/aggregator/mqtt/MqttSubmodelAggregatorHelper.java, src/main/java/org/eclipse/basyx/extensions/submodel/aggregator/mqtt/MqttSubmodelAggregatorObserver.java, src/main/java/org/eclipse/basyx/submodel/aggregator/observing/ISubmodelAggregatorObserver.java, src/main/java/org/eclipse/basyx/submodel/aggregator/observing/ObservableSubmodelAggregator.java, src/main/java/org/eclipse/basyx/submodel/observer/IObserver.java, src/main/java/org/eclipse/basyx/submodel/observer/Observable.java, src/main/java/org/eclipse/basyx/submodel/restapi/observing/ISubmodelAPIObserver.java, src/main/java/org/eclipse/basyx/submodel/restapi/observing/ObservableSubmodelAPI.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/aggregator/mqtt/TestMqttAASAggregatorObserver.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/submodel/aggregator/mqtt/TestMqttSubmodelAggregator.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/submodel/aggregator/mqtt/TestMqttSubmodelAggregatorObserver.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/aggregator/observing/ObservableSubmodelAggregatorTest.java
* Adds observer and observable aggregator of submodel
* Adds new constructors for MqttAggregator creation
* Adds corresponding tests
See https://github.com/eclipse-basyx/basyx-java-components/pull/22 for adjustments in components.
=> Adds MQTT functionality SubmodelAggregator

src/main/java/org/eclipse/basyx/submodel/factory/xml/XMLHelper.java, src/main/java/org/eclipse/basyx/submodel/factory/xml/converters/submodelelement/dataelement/PropertyXMLConverter.java, src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/dataelement/property/valuetype/ValueTypeHelper.java, src/test/java/org/eclipse/basyx/testsuite/regression/aas/factory/aasx/TestAASXToMetamodelConverterFromBaSyx.java
* Adds according test
* Adds Integer to ValueTypeHelper.getJavaObject
Co-authored-by: Daniel Espen <Daniel.Espen@iese.fraunhofer.de>
=> Fixes unexpected behaviour for deserialization of primitive datatypes

src/main/java/org/eclipse/basyx/aas/registration/proxy/AASRegistryProxy.java, src/main/java/org/eclipse/basyx/vab/registry/proxy/VABRegistryProxy.java
Co-authored-by: Jannis Jung <jannis.jung@iese.fraunhofer.de>
Signed-off-by: Rene-Pascal Fischer <rene-pascal.fischer@iese.fraunhofer.de>
=> Adds HTTPSConnector and corresponding check to registryProxies

src/main/java/org/eclipse/basyx/submodel/restapi/SubmodelAPIHelper.java, src/main/java/org/eclipse/basyx/submodel/restapi/SubmodelProvider.java, src/main/java/org/eclipse/basyx/submodel/restapi/vab/VABSubmodelAPI.java
=> Harmonizes path handling for sync/async invocation

src/main/java/org/eclipse/basyx/submodel/metamodel/facade/SubmodelElementMapCollectionConverter.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/facade/TestSubmodelElementMapCollectionConverter.java
=> Fixes wrong conversion of Entity statement

src/main/java/org/eclipse/basyx/aas/metamodel/map/AasEnv.java, src/test/java/org/eclipse/basyx/testsuite/regression/aas/metamodel/map/TestAasEnv.java
The missing initialization of Lists led to NullpointerExceptions in some scenarios.
Signed-off-by: Maximilian Conradi <maximilian.conradi@iese.fraunhofer.de>
=> Fixes missing initialization of Lists in AasEnv

src/main/java/org/eclipse/basyx/aas/aggregator/AASAggregatorAPIHelper.java, src/main/java/org/eclipse/basyx/aas/aggregator/proxy/AASAggregatorProxy.java, src/main/java/org/eclipse/basyx/aas/manager/ConnectedAssetAdministrationShellManager.java, src/main/java/org/eclipse/basyx/vab/modelprovider/VABPathTools.java, src/test/java/org/eclipse/basyx/testsuite/regression/aas/manager/TestConnectedAssetAdministrationShellManager.java
=> Fixes missing URL harmonization in ConnectedAASManager

src/main/java/org/eclipse/basyx/submodel/factory/xml/XMLHelper.java, src/test/java/org/eclipse/basyx/testsuite/regression/aas/factory/aasx/TestAASXToMetamodelConverterFromBaSyx.java
Signed-off-by: Daniel Espen <Daniel.Espen@iese.fraunhofer.de>
=> Fixes handling empty booleans in AASXToMetamodelConverter

src/main/java/org/eclipse/basyx/extensions/aas/directory/tagged/observing/ObservableAASTaggedDirectoryService.java, src/main/java/org/eclipse/basyx/extensions/aas/directory/tagged/restapi/TaggedDirectoryProvider.java
Signed-off-by: Daniel Espen <Daniel.Espen@iese.fraunhofer.de>
=> Adds ObservableService for TaggedDirectory

src/test/java/org/eclipse/basyx/testsuite/regression/submodel/aggregator/SubmodelAggregatorSuite.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/aggregator/TestInMemorySubmodelAggregator.java
=> Adds missing test suite for ISubmodelAggregator

src/main/java/org/eclipse/basyx/extensions/aas/directory/tagged/authorized/AuthorizedTaggedDirectory.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/directory/tagged/authorized/TestTaggedDirectoryAuthorization.java
Signed-off-by: Jannik Fried <Jannik.Fried@iese.fraunhofer.de>
=> Adds authorization for Tagged Directory

pom.xml, src/main/java/org/eclipse/basyx/vab/protocol/http/server/BaSyxHTTPServer.java
This PR updates Apache Tomcat version from 8.5.41 to 9.0.64.
This PR addresses the issue (#77 )
=> Updates Tomcat version to 9.0.64

src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/directory/tagged/TestTaggedDirectorySuite.java
=> Adds missing Descriptor removal

src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/dataelement/property/Property.java, src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/dataelement/property/valuetype/ValueTypeHelper.java, src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/dataelement/range/Range.java, src/main/java/org/eclipse/basyx/submodel/restapi/PropertyProvider.java, src/test/java/org/eclipse/basyx/testsuite/regression/aas/factory/aasx/TestAASXToMetamodelConverterFromBaSyx.java, src/test/java/org/eclipse/basyx/testsuite/regression/aas/factory/json/TestJSONConverter.java, src/test/java/org/eclipse/basyx/testsuite/regression/aas/factory/xml/TestXMLConverter.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/TestSubmodelSuite.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/connected/TestConnectedProperty.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/connected/submodelelement/dataelement/TestConnectedRange.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/map/submodelelement/dataelement/range/TestRange.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/map/submodelelement/operation/AsyncOperationHelper.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/map/submodelelement/operation/TestOperationSuite.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/map/support/TestAASLambdaPropertyHelper.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/restapi/TestPropertyProvider.java
=> Fixes value conversion on Property retrieval

src/main/java/org/eclipse/basyx/aas/registration/observing/ObservableAASRegistryService.java
=> Fixes missing call propagation

pom.xml, src/main/java/org/eclipse/basyx/vab/protocol/http/connector/HTTPConnector.java, src/main/java/org/eclipse/basyx/vab/protocol/http/connector/OAuth2ClientCredentialsBasedAuthorizationSupplier.java, src/main/java/org/eclipse/basyx/vab/protocol/https/JerseyHttpsClientFactory.java, src/test/java/org/eclipse/basyx/testsuite/regression/vab/protocol/http/TestHttpCors.java, src/test/java/org/eclipse/basyx/testsuite/regression/vab/protocol/http/TestVABHTTP.java, src/test/java/org/eclipse/basyx/testsuite/regression/vab/protocol/https/TestHTTPSVerification.java, src/test/java/org/eclipse/basyx/testsuite/regression/vab/protocol/https/TestVABHTTPS.java
javax.ws.rs was moved to jakarta.ws.rs therefore replaced javax dependency with latest jakarta version
=> javax replaced with jakarta

src/main/java/org/eclipse/basyx/vab/protocol/http/server/BasysHTTPServlet.java, src/test/java/org/eclipse/basyx/testsuite/regression/vab/protocol/http/TestHttpCors.java
=> Adds "Content-type" header to CORS config

src/main/java/org/eclipse/basyx/extensions/submodel/mqtt/MqttSubmodelAPIHelper.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/submodel/mqtt/MqttSubmodelAPIHelper.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/submodel/mqtt/TestMqttSubmodelAPI.java
Signed-off-by: Jannik Fried <Jannik.Fried@iese.fraunhofer.de>
=> Fixes exception when a submodel without parent reference is loaded when using MQTT

src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/aggregator/aasxupload/TestAASAggregatorAASXUploadSuite.java
=> Fixes test being dependent on AAS order

pom.xml, src/main/java/org/eclipse/basyx/vab/protocol/http/connector/HTTPConnector.java, src/main/java/org/eclipse/basyx/vab/protocol/http/connector/OAuth2ClientCredentialsBasedAuthorizationSupplier.java, src/main/java/org/eclipse/basyx/vab/protocol/https/JerseyHttpsClientFactory.java, src/test/java/org/eclipse/basyx/testsuite/regression/vab/protocol/http/TestHttpCors.java, src/test/java/org/eclipse/basyx/testsuite/regression/vab/protocol/http/TestVABHTTP.java, src/test/java/org/eclipse/basyx/testsuite/regression/vab/protocol/https/TestHTTPSVerification.java, src/test/java/org/eclipse/basyx/testsuite/regression/vab/protocol/https/TestVABHTTPS.java
Reverts eclipse-basyx/basyx-java-sdk#109
=> Revert "javax replaced with jakarta"

src/main/java/org/eclipse/basyx/submodel/metamodel/map/qualifier/LangStrings.java, src/main/java/org/eclipse/basyx/submodel/metamodel/map/qualifier/qualifiable/Qualifiable.java, src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/dataelement/range/Range.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/map/qualifier/TestLangStrings.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/map/qualifier/qualifiable/TestQualifiable.java
With this change the affected classes can allow predictable order for the get Methods
=> Predictable get order

src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/entity/Entity.java
=> Corrects typo in Entity statement handling

src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/dataelement/property/valuetype/ValueType.java
=> Fixes wrong anyURI string representation

src/main/java/org/eclipse/basyx/submodel/metamodel/facade/ElementContainerValuesHelper.java, src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/entity/Entity.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/map/TestElementContainerValuesHelper.java
=> Fixes wrong statement handling in valuesOnly calls

src/main/java/org/eclipse/basyx/submodel/restapi/observing/ObservableSubmodelAPIV2.java, src/main/java/org/eclipse/basyx/submodel/restapi/observing/ObservableSubmodelAPIV2Helper.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/submodel/mqtt/MqttV2SubmodelAPIObserverTest.java
=> Fixes typo in name of ObservableSubmodelAPIV2Helper

pom.xml
=> Fixes logging

src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/dataelement/property/Property.java, src/test/java/org/eclipse/basyx/testsuite/regression/TestSubmodelElementWithNullValue.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/connected/submodelelement/TestConnectedSubmodelElementFactory.java
Co-authored-by: Zai Zhang <zai.mueller-zhang@iese.fraunhofer.de>
=> Fixes crash related to properties with null as value

src/main/java/org/eclipse/basyx/extensions/shared/authorization/internal/BaSyxObjectTargetInformation.java, src/main/java/org/eclipse/basyx/extensions/shared/authorization/internal/ElevatedCodeAuthentication.java, src/main/java/org/eclipse/basyx/extensions/shared/authorization/internal/GrantedAuthorityInhibitException.java, src/main/java/org/eclipse/basyx/extensions/shared/authorization/internal/InhibitException.java, src/main/java/org/eclipse/basyx/extensions/shared/authorization/internal/SimpleRbacInhibitException.java, src/main/java/org/eclipse/basyx/extensions/shared/authorization/internal/TagTargetInformation.java, src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/dataelement/property/valuetype/ValueTypeHelper.java, src/main/java/org/eclipse/basyx/vab/coder/json/metaprotocol/Result.java, src/main/java/org/eclipse/basyx/vab/coder/json/serialization/GSONTools.java, src/main/java/org/eclipse/basyx/vab/protocol/http/connector/OAuth2ClientCredentialsBasedAuthorizationSupplier.java, src/main/java/org/eclipse/basyx/vab/protocol/http/server/BaSyxHTTPServer.java, src/test/java/org/eclipse/basyx/testsuite/regression/extensions/aas/aggregator/aasxupload/TestAASAggregatorAASXUploadSuite.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/connected/TestConnectedSubmodel.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/connected/submodelelement/dataelement/TestConnectedRange.java, src/test/java/org/eclipse/basyx/testsuite/regression/submodel/metamodel/map/submodelelement/dataelement/property/TestProperty.java, src/test/java/org/eclipse/basyx/testsuite/regression/vab/modelprovider/SimpleVABElement.java
=> Removes warnings

src/main/java/org/eclipse/basyx/submodel/factory/xml/XMLHelper.java, src/main/java/org/eclipse/basyx/submodel/metamodel/map/qualifier/qualifiable/Qualifier.java, src/test/java/org/eclipse/basyx/testsuite/regression/aas/factory/aasx/TestAASXToMetamodelConverterFromBaSyx.java
Co-authored-by: Eduardo Buitrago <eduardo.buitrago@objective-partner.com>
=> Fixes qualifier XML parsing bug

src/main/java/org/eclipse/basyx/submodel/aggregator/api/ISubmodelAggregatorFactory.java
Signed-off-by: Jannik Fried <Jannik.Fried@iese.fraunhofer.de>
=> Adds method required for automatic registration of Shells/Submodels

src/main/java/org/eclipse/basyx/aas/factory/xml/XMLToMetamodelConverter.java, src/main/java/org/eclipse/basyx/aas/factory/xml/converters/AssetAdministrationShellXMLConverter.java, src/test/java/org/eclipse/basyx/testsuite/regression/aas/factory/aasx/TestAASXToMetamodelConverterFromBaSyx.java
- Addresses issue eclipse-basyx/basyx-java-components#312
- Verified on the provided AASX file on the issue eclipse-basyx/basyx-java-components#312
The AAS contains referenced Asset now:
`[
{
"modelType": {
"name": "AssetAdministrationShell"
},
"idShort": "EmptyAAS",
"identification": {
"idType": "Custom",
"id": "AssetAdministrationShell---3BA03D1D"
},
"dataSpecification": [],
"embeddedDataSpecifications": [],
"submodels": [
{
"keys": [
{
"type": "AssetAdministrationShell",
"local": false,
"value": "AssetAdministrationShell---3BA03D1D",
"idType": "Custom"
},
{
"type": "Submodel",
"local": true,
"value": "https://example.com/ids/sm/8424_0101_3032_4185",
"idType": "IRI"
}
]
}
],
"asset": {
"keys": [
{
"type": "Asset",
"local": true,
"value": "https://empty.com",
"idType": "IRI"
}
], …
=> Fixes empty Asset

src/main/java/org/eclipse/basyx/extensions/shared/authorization/internal/RbacRuleSetDeserializer.java
- Can read rbac rules file from file system
=> Fix read rbac rules file

pom.xml
Closes https://github.com/eclipse-basyx/basyx-java-sdk/issues/267
=> Specifies dependency scope more precisely

src/main/java/org/eclipse/basyx/vab/protocol/http/server/BaSyxChildContext.java, src/main/java/org/eclipse/basyx/vab/protocol/http/server/BaSyxContext.java, src/main/java/org/eclipse/basyx/vab/protocol/http/server/BaSyxHTTPServer.java
Addresses the issue (eclipse-basyx/basyx-java-components#329)
=> Fixes files not served issue

src/main/java/org/eclipse/basyx/aas/manager/ConnectedAssetAdministrationShellManager.java
* First, remove from registry, then from AAS Server
=> Fixes order of AAS/Submodel deletion

src/main/java/org/eclipse/basyx/submodel/metamodel/map/dataspecification/EmbeddedDataSpecification.java
Generalised EmbeddedDataSpecification to comply not only with the IEC 61360 template
=> Generalised EmbeddedDataSpecification
